version: '3'

services:
  app:
    image: engincan/kap-members-db:1.0
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mypostgress123
      - LOG_LEVEL=10
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypostgress123
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: